version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  # version newest 7.8.0
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  ddosdb:
    build: .
    container_name: ddosdb
    command: python manage.py runserver 0.0.0.0:4000
    ports:
      - 4000:4000
    volumes:
      - ddosdb-data:/app/storage

  housekeeping:
    build: ./housekeeping
    depends_on:
      - elasticsearch
        #    command: /app/ddosdb-docker.db
        #    command: >
        #      /bin/bash -c "
        #        while ! curl elasticsearch:9200;
        #
        #        do
        #          echo elasticsearch service probably not ready yet..;
        #          sleep 1;
        #        done;
        #
        #        echo elasticsearch ready, time to boostrap!;
        #        /app/ddosdb-docker.db
        #      "

volumes:
  elasticsearch-data:
    driver: local
  ddosdb-data:
    driver: local
